version: '2'

services:
  app:
    image: 'ch-tv-plan'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=antilef
      - SPRING_DATASOURCE_PASSWORD=antilef
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
  db:
    image: 'postgres:16'
    container_name: db
    environment:
      - POSTGRES_USER=antilef
      - POSTGRES_PASSWORD=antilef
    volumes:
      - ../data:/var/lib/postgresql
